name: after_tests

on:
  workflow_run:
    workflows: [run_tests]
    types:
      - completed


jobs:
  after_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run after tests
        run: echo "ran after tests" 